unique_ids:
  forms:
    Form1: OJT73PR6TLQPTYYJVWZ35DP2ZBXDYP6X
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: RK33UHPRR53REL4G24SXD5EBRMSP24V2
    theme.css: YNMOBX46JMJM3GUPRF7PB2A5S2DK6RVY
  scripts: {}
